vcpkg_download_distfile(ARCHIVE
    URLS "https://reqrypt.org/download/WinDivert-2.2.2-A.zip"
    FILENAME "WinDivert-2.2.2-A.zip"
    SHA512 92eb2ef98ced175d44de1cdb7c52f2ebc534b6a997926baeb83bfe94cba9287b438f796aff11f6163918bcdbc25bcd4e3383715f139f690d207ce219f846a345
    DOWNLOAD_DIR ${CURRENT_BINARY_DIR}
)

vcpkg_extract_source_archive_ex(
    OUT_SOURCE_PATH SOURCE_PATH
    ARCHIVE ${ARCHIVE} 
)

file(INSTALL ${SOURCE_PATH}/include DESTINATION ${CURRENT_PACKAGES_DIR})

file(GLOB LIB_FILES ${SOURCE_PATH}/x64/*.lib)
file(INSTALL ${LIB_FILES} DESTINATION ${CURRENT_PACKAGES_DIR}/lib)

file(INSTALL ${LIB_FILES} DESTINATION ${CURRENT_PACKAGES_DIR}/debug/lib)

file(GLOB SYS_FILES ${SOURCE_PATH}/x64/*.sys)
file(INSTALL ${SYS_FILES} DESTINATION ${CURRENT_PACKAGES_DIR}/bin)
file(INSTALL ${SYS_FILES} DESTINATION ${CURRENT_PACKAGES_DIR}/debug/bin)

file(GLOB DLL_FILES ${SOURCE_PATH}/x64/*.dll)
file(INSTALL ${DLL_FILES} DESTINATION ${CURRENT_PACKAGES_DIR}/bin)
file(INSTALL ${DLL_FILES} DESTINATION ${CURRENT_PACKAGES_DIR}/debug/bin)

file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/windivert RENAME copyright)
